### ISSUE TITLE
Should the default year be changed to 2023?

### ISSUE THREAD

**Issue by stevencrader** [CFBD/cfb-web-v2#1]
I was going to create a PR to update the default year to 2023 but wanted to check before creating a PR.

I notice the page https://collegefootballdata.com/boxscore defaults to 2022. Now that football games have started for 2023, should it default to 2023?

https://github.com/CFBD/cfb-web-v2/blob/c5731335a4eca4a1e191f3b69fc6ecefee57b8d6/src/stores/main.ts#L49

**Comment by BlueSCar** [comment]
Yes. It's been updated now. It was initially set to 2022 until data could be populated for 2023 but we're now well past that threshold.
